version: '1.0.{build}'
image: Visual Studio 2017
before_build:
- choco install opencover.portable
- dotnet restore
- nuget restore ./packages.tools.config -OutputDirectory ./Packages
build_script:
  cmd: dotnet build 
test_script:
  ps: ./RunUnitTest.ps1
     